#!/usr/bin/env perl
use Mojolicious::Lite;

use lib qw(./Mojolicious-Plugin-MozPersona/lib);

plugin 'MozPersona' => {
    audience => 'http://127.0.0.1:3000/',
    siteName => 'My spectacular new site!',
};

get '/' => sub {
    my $self = shift;

    $self->render('index');
};


app->start;

__DATA__

@@ index.html.ep
<!DOCTYPE html>
<html>
  <head>
    <title>Mozilla Persona Test</title>
  </head>
  <body>
% if ( defined(session '_persona') && (session '_persona')->{'status'} eq 'okay' ) {
%     my $email = (session '_persona')->{'email'};
    <a href="#" class="persona-button" id="personaSignout"><span><%= $email %> abmelden</span></a>
% } else {
    <a href="#" class="persona-button" id="personaSignin"><span>Anmelden mit Ihrer Email</span></a>
% }
    <h1>Inhalt</h1>
    <p>
      Just some fake content
    </p>
  </body>
</html>
